# Rename me
service: template

plugins:
  - serverless-webpack
  - serverless-offline
  - seasketch-sls-geoprocessing
  - serverless-log-forwarding

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  memorySize: 512 # Default memory size. Can be set in individual functions too
  region: us-west-2
  environment:
    RESULTS_SQS_ENDPOINT:
      Fn::ImportValue: ReportResultsQueueEndpoint
    S3_BUCKET:
      Fn::ImportValue: ReportOutputs
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    # [todo] this stuff should probably be handled by the plugin...
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        Fn::ImportValue: ReportResultsQueueArn

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  logForwarding:
    destinationARN:
      Fn::ImportValue: "ReportLogsForwarder"

package:
  individually: true
