# Rename me
service: template

plugins:
  - serverless-webpack
  - serverless-offline
  - seasketch-sls-geoprocessing

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  memorySize: 512 # Default memory size. Can be set in individual functions too

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true
