# Rename me
service: SeaSketchReportingCore

provider:
  name: aws
  runtime: nodejs8.10
  stage: geoprocessing
  memorySize: 512 # Default memory size. Can be set in individual functions too
  region: us-west-2

  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        Fn::GetAtt:
          - LogQueue
          - Arn

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

functions:
  forwarder:
    handler: src/forwarder.handler
    memorySize: 128
    environment:
      SQS_ENDPOINT:
        Ref: LogQueue

resources:
  Resources:
    ReportOutputs:
      # AccessControl: PublicRead
      Type: AWS::S3::Bucket
    ReportOutputsBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        PolicyDocument:
          Id: ReportOutputsBucketPolicyDoc
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: ReportOutputs
                    - /*
        Bucket:
          Ref: ReportOutputs
    ForwarderLambdaPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName:
          Fn::GetAtt:
            - ForwarderLambdaFunction
            - Arn
        Principal: logs.${self:provider.region}.amazonaws.com
    LogQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        DelaySeconds: 0
        MaximumMessageSize: 262144 # 256kb
        MessageRetentionPeriod: 86400 # 1 day in seconds
        QueueName: ReportsLogQueue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 30 # seconds
    ResultsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        DelaySeconds: 0
        MaximumMessageSize: 262144 # 256kb
        MessageRetentionPeriod: 86400 # 1 day in seconds
        QueueName: ReportResultsQueue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 10 # seconds
  Outputs:
    ReportOutputsBucket:
      Description: s3 bucket
      Value:
        Ref: ReportOutputs
      Export:
        Name: ReportOutputs
    LogForwarder:
      Description: Cloudwatch Log forwarder
      Value:
        Fn::GetAtt:
          - ForwarderLambdaFunction
          - Arn
      Export:
        Name: ReportLogsForwarder
    LogQueueArn:
      Description: sqs queue arn for logs
      Value:
        Fn::GetAtt:
          - LogQueue
          - Arn
      Export:
        Name: ReportsLogQueueArn
    ResultsQueueArn:
      Description: sqs queue arn for report results
      Value:
        Fn::GetAtt:
          - ResultsQueue
          - Arn
      Export:
        Name: ReportResultsQueueArn
    ResultsQueueEndpoint:
      Description: sqs queue endpoint for report results
      Value:
        Ref: ResultsQueue
      Export:
        Name: ReportResultsQueueEndpoint
